In [4]:
import numpy as np

# uploading the salrary.csv file in salaries array

salaries=np.genfromtxt('salary.csv',delimiter=',')
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [5]:
# validating the count of rows in sheet
salaries.shape

(1147,)

In [7]:
# Statistical operation

# mean
mean=np.mean(salaries)
print(mean)

55894.53879686138


In [9]:
#median

median=np.median(salaries)
median

48000.0

In [10]:
#standard deviation

std=np.std(salaries)
std

55170.37550939316

In [13]:
#varians

var=np.var(salaries)
var

3043770333.8474483

In [18]:
#indexing and slicing

a=np.arange(11)**3
print(a)
a

[   0    1    8   27   64  125  216  343  512  729 1000]


array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [19]:
a[3]

27

In [20]:
a[1:5]

array([ 1,  8, 27, 64], dtype=int32)

In [28]:
print(a[-11:-1])

[  0   1   8  27  64 125 216 343 512 729]


In [29]:
print(a[::-1])

[1000  729  512  343  216  125   64   27    8    1    0]


In [30]:
print(a[-11:-1:2])

[  0   8  64 216 512]


In [35]:
print(a[-1:-11:-2])

[1000  512  216   64    8]


In [34]:
print(a[-1::-2])

[1000  512  216   64    8    0]


In [36]:
# multi-dimensioanl array

student=np.array([['swetha','sravanthi','amith','vijy'],
                  [50,60,70,80],
                  [80,70,60,50]
                 ])
student.shape


(3, 4)

In [37]:
print(student[0])

['swetha' 'sravanthi' 'amith' 'vijy']


In [38]:
print(student[1])

['50' '60' '70' '80']


In [39]:
print(student[2])

['80' '70' '60' '50']


In [54]:
# print swetha details
print(f"Name: {student[0][0].title()} \nSub1: {student[1][0]} \nSub2: {student[2][0]}")


Name: Swetha 
Sub1: 50 
Sub2: 80
